### ISSUE TITLE
amir says make forum, sounds reasonable

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PythonTurtle#43]

**Comment by bittner** [comment]
We could add a Gitter chat. That's easy, lightweight and done in a minute.

It's even possible to add the very same chat room as a "[sidecar](https://sidecar.gitter.im/)" to the website!  :trophy: (see the [Chocolatey website](https://chocolatey.org/) for a real-world example)

**Comment by cool-RR** [comment]
Nah, I'm not into that so much now. (This ticket is a decade old, like most of the tickets you replied on now.)

**Comment by bittner** [comment]
I like Gitter a lot, though. It feels very light and it there's a very low barrier to people to join the conversion. Yet still, it seems like chat SPAM is almost non-existent; probably because the audience is really tech-savvy developers.

Take these examples, and make up your mind (again):

1. [Django](https://gitter.im/django/django) (high traffic)
1. [LEGO ev3dev](https://gitter.im/ev3dev/chat) (medium traffic)
1. [pyenv](https://gitter.im/yyuu/pyenv) (medium-low traffic)
1. [behave BDD](https://gitter.im/behave/behave) (low traffic)
1. [behave-django](https://gitter.im/behave/behave-django) (even less traffic)

The chat is integrated with GitHub, which makes it easy to refer to issues, PRs and commits.

Some repos [add a badge](https://github.com/behave/behave-django#behave-django-) on top of the README to signal that this communication channel is available.

**Comment by cool-RR** [comment]
Okay, sounds good, feel free to create one and add that badge if you'd like.

**Comment by cool-RR** [comment]
Cool, created.

**Comment by bittner** [comment]
If you care about adding the forum also to your website simply add the following code at the end of the document's `<body>`:
```html
<script>
((window.gitter = {}).chat = {}).options = {room: 'PythonTurtle/Lobby'};
</script>
<script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
```
(from: https://sidecar.gitter.im/)
